theopenco/llmgateway

.github/workflows/ci.yml, .github/workflows/run.yml
Extracted repetitive CI logic into a reusable workflow 'run.yml'. Simplified 'ci.yml' by referencing the reusable workflow for lint, build, and test steps.
=> feat(ci): modularize and reuse workflows with inputs

.github/workflows/ci.yml, apps/docs/package.json, package.json, packages/db/package.json, turbo.json
Added the ability to configure migration file prefixes using "unix".
=> feat(db): add migration prefix configuration

apps/api/src/content/keys-api.ts, apps/api/src/content/keys-provider.ts, apps/api/src/content/logs.ts, packages/db/package.json, pnpm-lock.yaml
=> revert(chore/deps): bump the drizzle group with 2 updates

apps/ui/src/routes/dashboard/_layout/index.tsx
Added a muted placeholder text to loading state in dashboard layout for improved visual feedback.
=> fix(layout): add placeholder text for loading state

apps/ui/src/components/api-keys/api-keys-list.tsx
Removed "Last Used" and "Restrictions" columns to simplify the UI.
=> refactor(api-keys): remove unused table columns

apps/ui/src/components/usage/error-rate-chart.tsx, apps/ui/src/components/usage/usage-chart.tsx, apps/ui/src/lib/components/button.tsx
Updated ErrorRateChart and UsageChart to use the shared Button component for consistency and maintainability. Added `cursor-pointer` to button styles for better UX.
=> refactor(button): replace button elements with Button component

apps/ui/package.json, apps/ui/src/components/usage/cost-breakdown-chart.tsx, packages/models/src/providers.ts, pnpm-lock.yaml
Added color property to providers in @openllm/models and integrated it into the cost breakdown chart UI for enhanced visual representation.
=> feat(ui): integrate provider colors into cost chart

apps/ui/src/components/usage/cost-breakdown-chart.tsx, apps/ui/src/lib/components/select.tsx, apps/ui/src/lib/components/tabs.tsx
Updated multiple components (tabs, select, etc.) to use the `cursor-pointer` style for better UX. Refactored cost-breakdown-chart to replace custom button with standardized Button component.
=> fix(ui): improve accessibility with cursor-pointer changes

apps/ui/src/routes/dashboard/_layout.tsx, apps/ui/src/routes/dashboard/_layout/index.tsx, apps/ui/src/routes/login.tsx, apps/ui/src/routes/signup.tsx
Added authentication-based redirection to protect routes. Unauthenticated users are redirected to login, while logged-in users are redirected to the dashboard where applicable.
=> feat(auth): add session-based route redirection

packages/db/migrations/0000_small_nextwave.sql, packages/db/migrations/meta/0000_snapshot.json, packages/db/migrations/meta/_journal.json
Introduce tables for core entities including account, api_key, log, organization, passkey, project, and user-related data. Includes constraints, foreign keys, and default values to define database structure.
=> feat(db): add initial database schema and migration files

package.json, packages/db/package.json
Added `migrate` script for easier database migrations using pnpm and drizzle-kit in root and db package.json files.
=> chore(scripts): add migrate script to package.json files

packages/auth/src/auth.ts
Replaced hardcoded URLs with environment variables for improved flexibility and configurability in development and production environments.
=> fix(auth): update env variables for trusted origins

packages/auth/src/auth.ts
Refactored default URLs to use a single variable for consistency. Updated trustedOrigins to allow all origins ("*"). Improves flexibility and reduces environment-specific issues.
=> fix(auth): update default URL and trusted origins handling

Dockerfile
Added Tini to manage process signals effectively, enhancing runtime stability.
=> feat(Dockerfile): add Tini for improved process handling

tsup.config.ts
Added a JavaScript banner using createRequire for better module handling.
=> feat(tsup): add custom banner to output files

turbo.json
Updated input files in turbo.json to refine build dependencies.
=> chore(ci): update turbo.json inputs for build dependencies

eslint.config.mjs, package.json, tsup.config.ts, turbo.json
Simplified task inputs by introducing globalDependencies for clarity.
=> chore(config): update turbo.json with globalDependencies

.github/start.sh, Dockerfile, apps/api/src/serve.ts, apps/docs/app/api/search/route.ts, apps/docs/app/layout.tsx, apps/docs/next.config.mjs, apps/docs/package.json, apps/docs/tsconfig.json, apps/gateway/src/serve.ts, apps/ui/app.config.ts, apps/ui/package.json, infra/nginx-static.conf, turbo.json
Refactored build process and updated configurations to support static asset deployment with Nginx. Modified Dockerfile, app configs, and package scripts for static builds. Added Nginx configuration for serving static assets with caching and compression.
BREAKING CHANGE: Static deployment replaces previous runtime strategies.
=> feat(static-deployment): use static file hosting for UI apps

apps/ui/src/components/credits/payment-methods-management.tsx, apps/ui/src/components/credits/top-up-credits-dialog.tsx, apps/ui/src/lib/stripe.ts
Moved Stripe initialization to a shared utility function to improve code reuse and simplify configuration management.
=> feat(ui): centralize Stripe initialization logic

apps/gateway/openapi.json, apps/gateway/src/index.ts, apps/gateway/src/models/index.ts, apps/gateway/src/models/models.spec.ts, apps/gateway/src/models/models.ts
Introduce a new Models API to list and transform available models. Includes OpenAPI setup, routing updates, and test coverage.
=> feat(models): add models API with routing and tests

.github/workflows/run.yml
Ensure input command runs with strict error handling using set -eux.
=> ci: fix script execution in workflow run.yml

apps/ui/src/components/dashboard/activity-chart.tsx, apps/ui/src/components/dashboard/dashboard-sidebar.tsx, apps/ui/src/components/landing/code-example.tsx, apps/ui/src/components/landing/hero.tsx, apps/ui/src/components/landing/navbar.tsx, apps/ui/src/routes/dashboard/_layout/index.tsx, apps/ui/src/routes/index.tsx, apps/ui/src/routes/login.tsx, apps/ui/src/routes/signup.tsx
- Added multiple code examples to landing page
- Added a little dismissible card to buy credits to the sidebar footer
- Fixed mobile UI
- Close sidebar on mobile when navigating to a link
=> feat: add multiple code examples and cta to buy credits

apps/api/src/routes/keys-provider.ts, apps/gateway/src/api.e2e.ts, apps/gateway/src/chat/chat.ts, apps/ui/src/components/api-keys/create-api-key-dialog.tsx, apps/ui/src/components/landing/animated-beam.tsx, apps/ui/src/components/onboarding/credits-step.tsx, apps/ui/src/components/onboarding/provider-key-step.tsx, eslint.config.mjs, packages/models/src/provider-api.ts
Removed unnecessary variables and redundant function calls across multiple components for improved readability and maintainability. Updated ESLint rules to enforce unused variables prefixed with `_`.
=> refactor(api): clean up unused variables and redundant logic

.github/workflows/e2e.yml, packages/models/src/provider-api.ts
Convert `messages.content` from an array of objects into a concatenated string within `provider-api.ts`. Ensures compatibility with providers expecting string-based content.
ci(workflows): update e2e test paths for models
Refine path matching in `e2e.yml` to include all files under `packages/models/` for more targeted testing.
=> feat(models): transform message content to string array

.github/workflows/run.yml, apps/gateway/src/chat/chat.ts, apps/gateway/src/lib/provider.ts, apps/ui/src/assets/models/deepseek.svg, apps/ui/src/assets/models/perplexity.svg, apps/ui/src/components/provider-keys/provider-logo.ts, packages/models/src/models.ts, packages/models/src/provider-api.ts, packages/models/src/providers.ts
Integrate Perplexity as a supported provider in the models package. Includes updates to provider API, models list, provider logo assets, and related configurations.
=> feat(providers): add support for Perplexity provider

apps/gateway/src/chat/chat.ts
Return upstream error response text to client and unify logging format for chat completions.
=> fix(chat): handle chat completion errors and logging

apps/ui/src/components/api-keys/api-keys-list.tsx, apps/ui/src/components/dashboard/mobile-header.tsx, apps/ui/src/components/dashboard/top-bar.tsx, apps/ui/src/components/landing/github-stars.tsx, apps/ui/src/components/landing/navbar.tsx, apps/ui/src/components/models-supported.tsx, apps/ui/src/components/shared/product-hunt-banner.tsx, apps/ui/src/routes/changelog/index.tsx, apps/ui/src/routes/dashboard/_layout.tsx, apps/ui/src/routes/index.tsx, apps/ui/src/routes/login.tsx, apps/ui/src/routes/models.tsx, apps/ui/src/routes/providers/$id.tsx, apps/ui/src/routes/signup.tsx
- Updated various UI components to improve layout and responsiveness.
- Adjusted flex properties in `models-supported.tsx` for better alignment, restructured the `api-keys-list.tsx` to support both desktop and mobile views, and added a `ProductHuntBanner` to multiple routes for consistent branding. Additionally, refined header styles in `mobile-header.tsx` and `top-bar.tsx` for improved visibility and usability.
=> feat(ui): enhance layout and responsiveness across components

apps/ui/src/components/onboarding/onboarding-wizard.tsx, apps/ui/src/components/onboarding/plan-choice-step.tsx, apps/ui/src/components/onboarding/welcome-step.tsx
Refactor the onboarding flow to allow users to choose between buying credits or bringing their own keys (BYOK), clarifying BYOK requires a Pro plan.
=> fix(onboarding): improve credits vs BYOK flow

apps/ui/src/hooks/useUser.ts, apps/ui/src/routes/dashboard/_layout/index.tsx
Updated the Dashboard component to include loading states for organization data. Added checks to prevent rendering issues when organization data is still being fetched. Improved user experience by displaying a loading skeleton while data is being loaded.
Modified the `useUser` hook to also exclude the landing page from redirection logic, ensuring a smoother navigation experience for users.
=> fix(dashboard): enhance loading states and organization checks

.env.example, packages/auth/src/auth.ts
Introduced functionality to integrate Brevo for email campaigns. Added environment variables for Brevo configuration in `.env.example`. Updated auth flow to create Brevo contacts during user session creation.
=> feat(auth): add Brevo email campaigns integration

apps/api/src/serve.ts
Implemented signal handlers (`SIGTERM`, `SIGINT`) for clean shutdown of the server and database. Added error handling for uncaught exceptions and unhandled rejections to ensure stability during runtime.
=> feat(api): add graceful shutdown for server and database

.github/workflows/run.yml, apps/gateway/src/lib/provider.ts, packages/models/src/models.ts, packages/models/src/models/moonshot.ts, packages/models/src/provider-api.ts, packages/models/src/providers.ts
Integrated NovitaAI provider, including its API keys, endpoints, and support for streaming capabilities. Added "moonshot" models compatible with NovitaAI, detailing pricing, context size, and other specifications.
=> feat(models): add support for NovitaAI provider

apps/gateway/src/lib/provider.ts, packages/models/src/models/moonshot.ts, packages/models/src/provider-api.ts, packages/models/src/providers.ts
Integrated Moonshot AI provider into the system.
Includes updates to provider configurations, API handling, and model definitions. Added pricing, streaming, and context size details for Moonshot's kimi-k2 model variants.
=> feat(models): add support for Moonshot AI provider

.github/workflows/e2e.yml
Add branch-based cancellation to e2e.yml workflow to cancel pending runs on the same branch.
=> ci(e2e): add cancellation by branch name

.github/workflows/run.yml, apps/gateway/src/chat/chat.ts, apps/gateway/src/lib/provider.ts, packages/models/src/models.ts, packages/models/src/models/alibaba.ts, packages/models/src/provider-api.ts, packages/models/src/providers.ts
Integrated Alibaba Cloud as a new provider. Added Qwen models with details like pricing, context size, and streaming support. Updated provider configurations, API handling, workflows, and model definitions to accommodate Alibaba Cloud.
=> feat(providers): add support for Alibaba Cloud Qwen models

packages/models/src/models.ts, packages/models/src/models/alibaba.ts, packages/models/src/models/anthropic.ts, packages/models/src/models/deepseek.ts, packages/models/src/models/google.ts, packages/models/src/models/llmgateway.ts, packages/models/src/models/meta.ts, packages/models/src/models/mistral.ts, packages/models/src/models/moonshot.ts, packages/models/src/models/openai.ts, packages/models/src/models/perplexity.ts, packages/models/src/models/xai.ts
Enhanced model schema with a new `family` field for categorizing models. Updated all model configurations across multiple providers to include appropriate `family` values. Improved maintainability and organization of model definitions.
=> feat(models): add `family` field to model definitions

apps/gateway/src/lib/redis.ts, apps/gateway/src/worker.ts
Reverts theopenco/llmgateway#525
=> revert(fix(worker): ensure redis entries

apps/ui/src/components/dashboard/log-card.tsx
Added a new field to log cards showing the Request ID for logs. This improves log traceability and debugging by exposing unique identifiers.
=> feat(ui): display request ID in log card

apps/gateway/src/chat/chat.ts
Added email verification checks for users requesting access to free models. Throws HTTP exceptions if a user's email is not verified or if the user cannot be found in the organization's records.
=> feat(chat): enforce email verification for free models

infra/split.dockerfile, infra/unified.dockerfile
Introduced cache mounting for pnpm store to optimize performance and added a verification step to ensure correct pnpm store paths in Dockerfiles.
=> feat(infra): add pnpm store cache and verify paths
