.github/workflows/run.yml
Removed the lint step from the GitHub Actions workflow to streamline the process.
=> ci(workflows): remove lint step from workflow

.github/workflows/ci.yml
Removed the generate step in the CI pipeline as it is redundant.
=> ci: remove generate step from CI workflow

turbo.json
Disabled caching for the generate task in turbo.json to adjust task execution behavior.
=> chore(ci): disable caching for generate task

apps/api/src/content/keys-provider.ts, apps/gateway/src/chat/chat.ts, apps/ui/src/components/provider-keys/provider-keys-list.tsx, packages/db/src/schema.ts
Ensure only active provider keys are used in operations and exclude deleted keys from UI and queries.
BREAKING CHANGE: Removed unique constraint on provider keys schema.
=> fix(chat): filter provider keys by active/deleted status

.github/workflows/images.yml
Updated Docker image tag format to use github.repository for consistency and accuracy in CI workflows.
=> fix(ci): update repository tag format in images.yml

apps/ui/src/components/dashboard/dashboard-sidebar.tsx
Commented out the SidebarGroupLabel code as it is currently unused.
=> fix(dashboard): remove useeless SidebarGroupLabel hint

apps/gateway/src/chat/chat.ts, packages/db/migrations/0001_rapid_shinobi_shaw.sql, packages/db/migrations/meta/0001_snapshot.json, packages/db/migrations/meta/_journal.json, packages/db/src/schema.ts
Added "cached" property to log entries for better tracking of cache usage. Removed unnecessary console debug logs for cleaner output. Updated the database schema to include "cached" column in the "log" table.
=> feat(chat): add cached property for log entries

apps/gateway/src/api.spec.ts, apps/gateway/src/chat/chat.ts
Improved error messages to guide users to add provider keys or switch to credits/hybrid mode when no API key is set for a provider. Updated related test snapshots.
=> fix(chat): update error messages for provider key issues

packages/models/src/models.ts
Updated token pricing for GPT-3.5, GPT-4, and GPT-4o models. Added new models: GPT-4.1, GPT-4.1-mini, and GPT-4.1-nano.
=> feat(models): update pricing and add new GPT-4.1 models

.github/workflows/ci.yml
Added a condition to skip e2e tests for Dependabot commits.
=> ci(workflows): exclude Dependabot from e2e workflow

.env.example, apps/docs/app/(home)/[[...slug]]/page.tsx, docker-compose.prod.yml
Enabled dynamic `metadataBase` configuration using `VITE_DOCS_URL` in `page.tsx`. Updated `.env.example` and `docker-compose.prod.yml` to include `DOCS_PORT` configuration for hosting documentation in self-hosted setups.
=> feat(docs): add VITE_DOCS_URL support for dynamic metadataBase

apps/ui/src/components/models/models-list.tsx, apps/ui/src/lib/utils.ts, apps/ui/src/routes/models.tsx, packages/models/src/models.ts
Stacked PRs:
* __->__#297
--- --- ---
Added UI display for `contextSize` property in model cards and the
models list. Introduced `formatContextSize` utility for better
readability of large context values. Ensures easier visibility of
maximum token context window size in the interface.
=> feat(models): display context size in UI for models

packages/models/src/models.ts
Added `gemini-2.5-pro-preview-06-05` to `models.ts` with pricing, provider details, and context size for compatibility with latest offerings.
=> feat(models): add new 2.5 pro preview 06-05 gemini model

apps/gateway/src/lib/logs.ts
Applied logic to set `unifiedFinishReason` to `CANCELED` for logs where the `canceled` property is true. Ensures accurate representation of log statuses.
=> fix(logs): handle canceled logs with unified finish reason

apps/gateway/src/api.e2e.ts, apps/gateway/src/chat/chat.ts
Ensure `total_tokens` equals the sum of `prompt_tokens` and `completion_tokens` in API usage tests.
=> test(api): add assertion for token usage consistency

.github/workflows/images.yml
Replace branch-based triggers with release events. Use release tags for Docker image versions and streamline build steps by removing short SHA retrieval.
=> feat(ci): update workflow for release-based image builds

apps/ui/src/lib/env.ts, turbo.json
Replace `GITHUB_URL` with `VITE_GITHUB_URL` for alignment with other VITE-prefixed environment variables. Remove unused variables from turbo.json to streamline configuration.
=> fix(env): update env variable mappings for consistency

packages/models/src/models.ts, packages/models/src/models/perplexity.ts
Stacked PRs:
* #434
* __->__#433
--- --- ---
Extract Perplexity-related models into a separate module for improved modularity and maintainability.
Reuse `perplexityModels` in the main model definitions to streamline integration.
=> feat(models): modularize and extend Perplexity models

packages/models/src/models.ts, packages/models/src/models/perplexity.ts
Stacked PRs:
* __->__#434
* #433
--- --- ---
Added `sonar-reasoning-pro` and `sonar` models to `perplexityModels`.
Updated `sonar-pro` model's pricing and context size for accuracy.
Extended provider definitions to include `imageInputPrice`.
=> feat(models): add new Perplexity models with updated specs

apps/api/src/lib/beacon.ts, apps/api/src/routes/beacon.spec.ts, apps/api/src/routes/beacon.ts, infra/split.dockerfile, infra/unified.dockerfile
Migrate telemetry control from `DISABLE_TELEMETRY` to `TELEMETRY_ACTIVE` to switch to an opt-in model while maintaining default enablement for Docker deployments.
=> fix(telemetry): make telemetry opt-in with docker default

apps/api/src/stripe.ts
Ensure all `payment_intent.payment_failed` Stripe events create a failed transaction record.
The `handlePaymentIntentFailed` function now inserts a new transaction record with a 'failed' status if no existing pending transaction is found, or if the payment intent does not have a `transactionId` in its metadata (e.g., manual top-ups).
=> fix(credits): handle failed payment intents

apps/api/src/routes/user.ts, apps/ui/src/components/onboarding/onboarding-wizard.tsx, apps/ui/src/hooks/useUser.ts, apps/ui/src/lib/api/v1.d.ts, apps/ui/src/routes/login.tsx, apps/ui/src/routes/signup.tsx, packages/db/migrations/1751655634_naive_payback.sql, packages/db/migrations/meta/1751655634_snapshot.json, packages/db/migrations/meta/_journal.json, packages/db/src/schema.ts
Introduced `onboardingCompleted` property to the user schema and API routes. Added a new `/me/complete-onboarding` endpoint and integrated onboarding checks in the UI navigation logic. Updated database schema and migrations to persist onboarding status.
=> feat(user): add onboarding completion tracking

apps/ui/src/routes/dashboard/_layout/index.tsx
Introduced `shouldShowGetStartedState` logic to display a get started prompt for organizations with no credits and a non-pro plan. This enhances user guidance during the onboarding phase.
=> fix(ui): add get started state for new users

apps/ui/src/hooks/useUser.ts
Implement automatic onboarding redirect for incomplete users in `useUser` to ensure all authenticated users complete the process.
Previously, onboarding checks were opt-in. This change makes the check universal for authenticated users, automatically redirecting them to `/onboarding` if incomplete, while excluding auth pages to prevent redirect loops.
=> fix(onboarding): trigger onboarding redirect when incomplete

apps/api/src/lib/beacon.ts, apps/api/src/routes/beacon.spec.ts, apps/api/src/routes/beacon.ts, apps/ui/src/lib/api/v1.d.ts
Added validation and inclusion of the `version` field in the beacon schema and payload to ensure accurate version tracking. Removed `cloud_provider` as it is no longer required for the payload.
=> fix(beacon): include version in beacon payload

infra/split.dockerfile
The Dockerfile was manually creating .turbo cache directories in every app and package to prevent potential build errors with Turborepo. This was a temporary workaround, as noted by the comment:
`> “todo temp figure out a better solution”`
Manually creating these folders is unnecessary, adds boilerplate, and doesn’t provide any build cache benefits.
- Removes the manual mkdir commands for .turbo folders in the Dockerfile.
- Updates the build step to use Docker BuildKit’s cache mount for /app/.turbo:
` RUN --mount=type=cache,target=/app/.turbo pnpm build`
- Adds the BuildKit syntax directive at the top of the Dockerfile.
Using BuildKit cache mounts is the modern, recommended way to handle build caching with Turborepo in Docker.
This approach:
- Automatically creates the cache directory as …
=> chore(docker): use BuildKit cache mount for Turborepo instead of manual .turbo creation

apps/api/src/routes/keys-provider.ts, apps/docs/content/custom-providers.mdx, apps/gateway/src/api.e2e.ts, apps/gateway/src/chat/chat.ts, apps/gateway/src/lib/cache.ts, apps/gateway/src/lib/provider.ts, apps/next/.content-collections/generated/index.d.ts, apps/next/src/components/provider-keys/create-provider-key-dialog.tsx, apps/next/src/components/provider-keys/provider-keys-client.tsx, apps/next/src/components/provider-keys/provider-keys-list.tsx, apps/next/src/lib/api/v1.d.ts, apps/ui/src/components/provider-keys/create-provider-key-dialog.tsx, apps/ui/src/components/provider-keys/provider-logo.ts, apps/ui/src/lib/api/v1.d.ts, packages/db/migrations/1752885977_sleepy_prism.sql, packages/db/migrations/1753215645_organic_black_tarantula.sql, packages/db/migrations/meta/1752885977_snapshot.json, packages/db/migrations/meta/1753215645_snapshot.json, packages/db/migrations/meta/_journal.json, packages/db/src/schema.ts, packages/models/src/helpers.ts, packages/models/src/provider-api.ts, packages/models/src/providers.ts
Introduced "custom" provider type with configurable name and base URL. Updated schema, UI, API, and caching logic to handle custom providers. Ensured validation and model compatibility checks accommodate custom providers.
=> feat(providers): add support for custom OpenAI-compatible providers

infra/unified.dockerfile
**The Issue**
Following the successful implementation of Turbo build cache optimization in `split.dockerfile` (merged in previous PR), the `unified.dockerfile` was still missing the same performance optimization.
**What this PR changes**
Updates the build step in `unified.dockerfile` to use Docker BuildKit's cache mount for /app/.turbo:
`RUN --mount=type=cache,target=/app/.turbo pnpm build`
**Why I implemented this**
This completes the Turbo cache optimization across all Docker build contexts in the project. Using BuildKit cache mounts is the modern, recommended way to handle build caching with Turborepo in Docker.
This approach:
- Automatically creates the cache directory as needed
- Speeds up repeated builds by persisting cache between builds
- Provides consistent performance across …
=> feat: add Turbo build cache mount to unified.dockerfile

apps/gateway/src/index.ts
Replaced the default API server URL with "https://api.llmgateway.io" while retaining a fallback server option for local development.
=> feat(gateway): update API server URL configuration

apps/gateway/src/chat/chat.ts, apps/ui/src/components/dashboard/log-card.tsx
Support parsing both `reasoning_content` and `reasoning` fields to ensure compatibility with varying response formats.
=> fix(chat): handle alternative reasoning field names

infra/supervisord.conf, infra/unified.dockerfile
Replaced manual Redis build process in Dockerfile with `redis-server` package installation to simplify setup and improve build efficiency. Removed unnecessary build dependencies.
=> fix(infra): replace Redis build with package installation

apps/docs/package.json, pnpm-lock.yaml
Dropped `eslint` and `eslint-config-next` from the `apps/docs` directory and updated `pnpm-lock.yaml` to reflect dependency removals.
=> chore(docs): remove eslint and related dependencies

apps/ui/src/app/blog/[slug]/page.tsx, apps/ui/src/app/blog/category/[category]/page.tsx, apps/ui/src/app/blog/page.tsx, apps/ui/src/app/changelog/[slug]/page.tsx, apps/ui/src/app/changelog/page.tsx
Replaced static imports of `content-collections` with dynamic imports across blog and changelog pages to improve loading efficiency and resolve unused imports.
=> chore(ui): import collections dynamically for all pages
